services:
  postgres:
    container_name: project-template-postgres
    image: 'gekal/postgres:17-bullseye'
    build:
      dockerfile: database/Dockerfile
      context: .
    environment:
      - 'POSTGRES_DB=template'
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '15432:5432'
