x-db-config: &db-config
  POSTGRES_DB: &db-name template
  POSTGRES_USER: &db-user myuser
  POSTGRES_PASSWORD: &db-password secret

services:
  postgres:
    container_name: project-template-postgres
    image: 'gekal/postgres:15.10-bullseye'
    build:
      dockerfile: database/Dockerfile
      context: .
    environment:
      <<: *db-config
    ports:
      - '15432:5432'
    volumes:
      - ./database/initdb:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d template" ]
      interval: 10s
      timeout: 5s
      retries: 5

  migration:
    container_name: project-template-migration
    build:
      dockerfile: Dockerfile-migration
      context: .
    environment:
      ENV: &env dev
      DATASOURCE_URL: &db-url jdbc:postgresql://postgres:5432/template
      DATASOURCE_USERNAME: *db-user
      DATASOURCE_PASSWORD: *db-password
    depends_on:
      postgres:
        condition: service_healthy

  app:
    container_name: project-template-app
    build:
      dockerfile: Dockerfile-app
      context: .
    environment:
      ENV: *env
      SPRING_DATASOURCE_URL: *db-url
      SPRING_DATASOURCE_USERNAME: *db-user
      SPRING_DATASOURCE_PASSWORD: *db-password
    ports:
      - '18080:8080'
    depends_on:
      postgres:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://127.0.0.1:8080/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db:
