[environments]
url = "${env.DATASOURCE_URL}"
user = "${env.DATASOURCE_USERNAME}"
password = "${env.DATASOURCE_PASSWORD}"

[environments.flyway]
locations = [
    "classpath:db/migration/schema",
    "classpath:db/migration/data/${env.ENV}"
]
