[environments.dev]
url = "${env.DATASOURCE_URL}"
user = "${env.DATASOURCE_USERNAME}"
password = "${env.DATASOURCE_PASSWORD}"

[environments.dev.flyway]
locations = [
    "classpath:db/migration/schema",
    "classpath:db/migration/data/dev"
]

[environments.stg]
url = "${env.DATASOURCE_URL}"
user = "${env.DATASOURCE_USERNAME}"
password = "${env.DATASOURCE_PASSWORD}"

[environments.stg.flyway]
locations = [
    "classpath:db/migration/schema",
    "classpath:db/migration/data/stg"
]
