spring:
  application:
    name: "Project Template"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/template
    username: myuser
    password: secret

mybatis:
  type-aliases-package: cn.gekal.spring.template.domain.model
  type-handlers-package: cn.gekal.spring.template.infrastructure.config
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
